import type { User, Candidate, Interview } from './types';

export const users: User[] = [
  { name: 'Alice Johnson', email: 'alice@example.com', avatar: 'https://placehold.co/40x40.png?text=AJ' },
  { name: 'Bob Williams', email: 'bob@example.com', avatar: 'https://placehold.co/40x40.png?text=BW' },
  { name: 'Charlie Brown', email: 'charlie@example.com', avatar: 'https://placehold.co/40x40.png?text=CB' },
  { name: 'Diana Miller', email: 'diana@example.com', avatar: 'https://placehold.co/40x40.png?text=DM' },
];

export const candidates: Candidate[] = [
  {
    id: 'CAN-001',
    name: 'Sophia Davis',
    email: 'sophia.d@example.com',
    avatar: 'https://placehold.co/100x100.png?text=SD',
    role: 'Senior Frontend Developer',
    stage: 'Interviewing',
    appliedDate: '2023-10-15',
    qualifications: 'React, TypeScript, Next.js, GraphQL',
  },
  {
    id: 'CAN-002',
    name: 'Liam Martinez',
    email: 'liam.m@example.com',
    avatar: 'https://placehold.co/100x100.png?text=LM',
    role: 'Product Manager',
    stage: 'Offer',
    appliedDate: '2023-10-12',
    qualifications: 'Agile, Scrum, JIRA, Roadmapping',
  },
  {
    id: 'CAN-003',
    name: 'Olivia Garcia',
    email: 'olivia.g@example.com',
    avatar: 'https://placehold.co/100x100.png?text=OG',
    role: 'UX/UI Designer',
    stage: 'Hired',
    appliedDate: '2023-09-28',
    qualifications: 'Figma, Sketch, Adobe XD, Prototyping',
  },
  {
    id: 'CAN-004',
    name: 'Noah Rodriguez',
    email: 'noah.r@example.com',
    avatar: 'https://placehold.co/100x100.png?text=NR',
    role: 'Backend Engineer',
    stage: 'Applied',
    appliedDate: '2023-10-20',
    qualifications: 'Node.js, Python, PostgreSQL, AWS',
  },
  {
    id: 'CAN-005',
    name: 'Emma Wilson',
    email: 'emma.w@example.com',
    avatar: 'https://placehold.co/100x100.png?text=EW',
    role: 'Data Scientist',
    stage: 'Sourced',
    appliedDate: '2023-10-18',
    qualifications: 'Python, R, SQL, Machine Learning',
  },
    {
    id: 'CAN-006',
    name: 'James Taylor',
    email: 'james.t@example.com',
    avatar: 'https://placehold.co/100x100.png?text=JT',
    role: 'DevOps Engineer',
    stage: 'Interviewing',
    appliedDate: '2023-10-11',
    qualifications: 'Docker, Kubernetes, Jenkins, Terraform',
  },
  {
    id: 'CAN-007',
    name: 'Isabella Anderson',
    email: 'isabella.a@example.com',
    avatar: 'https://placehold.co/100x100.png?text=IA',
    role: 'Senior Frontend Developer',
    stage: 'Phone Screen',
    appliedDate: '2023-10-21',
    qualifications: 'Vue.js, Nuxt.js, TypeScript',
  },
];

export const interviews: Interview[] = [
  {
    id: 'INT-001',
    candidate: candidates[0],
    role: 'Senior Frontend Developer',
    date: '2023-10-25',
    time: '10:00 AM',
    panelists: [users[0], users[1]],
    status: 'Scheduled',
  },
  {
    id: 'INT-002',
    candidate: candidates[1],
    role: 'Product Manager',
    date: '2023-10-26',
    time: '2:00 PM',
    panelists: [users[2], users[3]],
    status: 'Scheduled',
  },
  {
    id: 'INT-003',
    candidate: candidates[5],
    role: 'DevOps Engineer',
    date: '2023-10-27',
    time: '11:00 AM',
    panelists: [users[1], users[2]],
    status: 'Scheduled',
  },
  {
    id: 'INT-004',
    candidate: candidates[2],
    role: 'UX/UI Designer',
    date: '2023-10-15',
    time: '3:00 PM',
    panelists: [users[0], users[3]],
    status: 'Completed',
  },
   {
    id: 'INT-005',
    candidate: candidates[3],
    role: 'Backend Engineer',
    date: '2023-10-28',
    time: '9:00 AM',
    panelists: [users[0], users[1]],
    status: 'Canceled',
  },
];
